### ISSUE TITLE
Allow wildcard for query params which you don't care about the value

### ISSUE THREAD

**Issue by E1200533** [hector-js/stub-backend#62]
**Is your feature request related to a problem? Please describe.**
The current problem I'm experiencing is that I want to define a mock request which has date query params, but I don't care about their value, I just want to return the same response always. Currently it seems like that isn't possible? 

**Describe the solution you'd like**
My ideal solution would be something like this:

```json
{
  "_get": {
    "/bank/accounts/{id}/transactions?fromBookingDateTime={p1}&toBookingDateTime={p2}": [
      {
        "_req": {
          "_id": "1234",
          "_p1": "*",
          "_p2": "*"
...
```

to indicate that the value of `p1` and `p2` can be anything. Or even omitting the `"_p1"` and `"_p2"` keys altogether.

**Describe alternatives you've considered**
Currently if I leave those keys out of the `"_req"` object, then I just get a 404 when I try to make the request.

**Additional context**
none

**Comment by E1200533** [comment]
I'm going to try and create a PR for this today

**Comment by E1200533** [comment]
PR up!

**Comment by hector-js** [comment]
Hi @E1200533 , I have upgraded README file and I have created two e2e scenarios as well.

**Comment by hector-js** [comment]
You can start using this feature in the following version:

[1.6.0](https://www.npmjs.com/package/@hectorjs/stub-backend/v/1.6.0)

**Comment by E1200533** [comment]
Amazing, thanks!
