### ISSUE TITLE
Run server with delays disabled

### ISSUE THREAD

**Issue by E1200533** [hector-js/stub-backend#73]
**Is your feature request related to a problem? Please describe.**
We currently use the mock server for two use cases:
- demonstrating the functionality of the app, where we want delays in order for the api calls to feel more realistic
- E2E testing, where we don't want delays, in order for the tests to run as fast as possible

**Describe the solution you'd like**
Ideally we can define delays in the resource files exactly as now, but when we run our E2Es we could optionally start the mock server with some kind of flag e.g. `--no-delays` which will ignore all the defined delays.

**Comment by hector-js** [comment]
Hi @E1200533, very good idea ! 😄 Let me have a look the merge request this afternoon and I will include it in the next release.
Thanks for the support

**Comment by hector-js** [comment]
FYI: @E1200533 , I opened an issue in the cli where you can execute the mocks without --no_delay flag like:

```hjs start --no_delays```

I will inform here once the new version is deployed

**Comment by hector-js** [comment]
Here you have the new version of for the cli:
https://www.npmjs.com/package/@hectorjs/stub-cli/v/1.12.0
